#*************************************************************************
#
# VERSION.INC - Version numbers and copyright notices for make files.
#
#*************************************************************************

FDR_VER_MAJOR=10
FDR_VER_MINOR=1
FDR_VER_BUILD=99
FDR_VER_STRING=10.1.99
FDR_LEGALCOPYRIGHT_STRING=(C) Copyright DummyCompany 2015. Portions (C) Copyright DumyCompany Corporation.
